version: "3" 
services:     
  web:         
    # replace username with your username         
    image: amalals/bulletinboard:1.0   #CHANGE      
    deploy:             
      replicas: 5             
      resources:                
        limits:                     
          cpus: "0.1"                     
          memory: 50M             
      restart_policy:                 
        condition: on-failure         
    ports:             
      - 8882:8080         
    networks:             
      - webnet 
networks:     
  webnet:
